import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from "../../public/images/profile/Main.jpeg"
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/icon'
import HireMe from '@/components/HireMe'
import lightbulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import TransitionEffect from '@/components/TransitionEffect'




export default function Home() {
  return (
   <>
      <Head>
        <title>Mahesh&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect/>
      <main className='flex items-center w-full min-h-screen text-dark dark:text-light'>
        <Layout className='pt-0 md:p-16 sm:pt-8'>
        <div className="flex items-center justify-between w-full lg:flex-col">
            {/* <div className='w-1/2 md:w-full'>
              <Image src={profilePic} alt="CodeBucks" className='w-full h-auto lg:hidden md:inline-block md:w-full' 
              priority
              sizes='(maz-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              50vw'
              />
            </div> */}
            <div className='relative col-span-3 p-8 mt-5 border-2 border-solid h-max rounded-2xl border-dark bg-light dark:bg-dark dark:border-light xl:col-span-4 md:order-1 md:col-span-8'>
    <div className='absolute top-0 -right-3 -z-10 w-[102%] h-[100%] rounded-2xl bg-dark dark:bg-light'/>
     <Image src={profilePic} alt="Mahesh" className='w-full h-auto rounded-2xl'
     priority
     sizes='(maz-width: 768px) 100vw,
     (max-width: 1200px) 50vw,
     33vw'/>
    </div>
            <div className='flex flex-col items-center self-center w-1/2 lg:w-full lg:text-center'>
               <AnimatedText text="Turning Vision Into Reality With Design And Code." className='!text-6xl text-left
               xl:!text-5xl lg:!text-center lg:!text6xl md:!text-5xl sm:!text-3xl
               
               '/>

                <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>
                I believe that good design is about more than just making things look pretty – it&apos;s about solving problems and 
creating intuitive, enjoyable experiences for users and making people&apos;s lives better. </p> 
<div className='flex items-center self-start mt-2 lg:self-center'>
  <Link href="/Mahesh Resume.pdf" target={"_blank"} className="flex items-center bg-dark text-light p-2.5 px-6
  rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
  border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
  hover:dark:border-light md:p-2 md:px-2 md:text-sm sm:text-xs
  "
  download={true}
  >Resume<LinkArrow className={"w-5 ml-1"}/>
  
  </Link>
  <Link href="mailto:itssmahesh.5@gmail.com" target={"_blank"}
  className="ml-4 text-lg font-medium underline capitalize text-dark dark:text-light md:text-base md:text-sm sm:text-xs"
  >Contact</Link>
</div>
     </div>
      </div>
        </Layout>

         <HireMe/>
         <div className='absolute inline-block w-24 right-8 bottom-8 md:hidden'>
           <Image src={lightbulb} alt="Mahesh" className='w-full h-auto'/>
         </div>
      </main>
    </>
  )
}
